package com.example.gumastha;

import android.content.Context;
import android.content.Intent;
import android.os.Parcelable;
import android.text.format.DateUtils;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;

import com.example.gumastha.Model.Transaction;

import org.jetbrains.annotations.NotNull;

import java.util.ArrayList;

public class transactionListAdapter extends RecyclerView.Adapter<transactionListAdapter.ViewHolder> {
    Context context;
    ArrayList<Transaction>list;
    View view;
    public transactionListAdapter(Context context, ArrayList<Transaction> list) {
        this.context=context;
        this.list=list;
    }

    @NonNull
    @NotNull
    @Override
    public ViewHolder onCreateViewHolder(@NonNull @NotNull ViewGroup parent, int viewType) {
        view= LayoutInflater.from(parent.getContext()).inflate(R.layout.transaction_item,parent,false);
        ViewHolder viewHolder=new ViewHolder(view);
        return viewHolder;
    }

    @Override
    public void onBindViewHolder(@NonNull @NotNull transactionListAdapter.ViewHolder holder, int position) {
        Transaction t=list.get(position);
        holder.itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent i=new Intent(context,Transaction_Display.class);
                i.putExtra("Transaction",t);
                context.startActivity(i);
            }
        });
        holder.totalproducts.setText("Transaction Id: "+t.TID);
        holder.paymentmode.setText(t.transactionMode);
        holder.amount.setText(String.valueOf(t.billAmount));
        holder.generatedby.setText("Generated By "+t.Generated_By);
        String Timeago= (String) DateUtils.getRelativeTimeSpanString(t.seconds*1000);
        holder.time.setText(Timeago);
    }

    @Override
    public int getItemCount() {
        return list.size();
    }

    public class ViewHolder extends RecyclerView.ViewHolder {
        TextView totalproducts,paymentmode,amount,generatedby,time;
        public ViewHolder(@NonNull @NotNull View itemView) {
            super(itemView);
            totalproducts=itemView.findViewById(R.id.total_products_transaction);
            paymentmode=itemView.findViewById(R.id.payment_mode_transaction);
            amount=itemView.findViewById(R.id.amount_transaction);
            time=itemView.findViewById(R.id.time);
            generatedby=itemView.findViewById(R.id.generated_by_transaction);
        }
    }
}
